// This file is generated by tools/gen_web_index.py from
// docs/config-ui-mockup.html. Do not edit by hand.

#pragma once

// Generated 2026-07-03T23:17:39 from docs/config-ui-mockup.html
// Source size: 36131 bytes
static const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0f1116">
<title>Combat Robot v2 — Settings</title>
<style>
  :root {
    --bg: #0f1116;
    --card: #1a1d24;
    --card-2: #20232c;
    --fg: #e6e9ef;
    --muted: #8a93a6;
    --accent: #ff6b35;
    --accent-2: #ffa066;
    --good: #4ade80;
    --warn: #fbbf24;
    --bad: #f87171;
    --border: #2a2f3a;
    --radius: 12px;
    --pad: 14px;
  }
  * { box-sizing: border-box; }
  html, body {
    margin: 0; padding: 0; background: var(--bg); color: var(--fg);
    font: 15px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }
  body { padding-bottom: env(safe-area-inset-bottom); }
  header {
    position: sticky; top: 0; z-index: 5; backdrop-filter: blur(10px);
    background: rgba(15,17,22,0.85); border-bottom: 1px solid var(--border);
    padding: calc(10px + env(safe-area-inset-top)) var(--pad) 10px;
    display: flex; align-items: center; justify-content: space-between;
  }
  header h1 { font-size: 17px; margin: 0; letter-spacing: 0.2px; }
  header .meta { font-size: 12px; color: var(--muted); }
  .dot { width: 10px; height: 10px; border-radius: 50%; display: inline-block; vertical-align: middle; margin-right: 4px; }
  .dot.on { background: var(--good); box-shadow: 0 0 8px var(--good); }
  .dot.off { background: var(--muted); }

  /* Tabs */
  nav.tabs {
    display: flex;
    position: sticky; top: 51px; z-index: 4;
    background: rgba(15,17,22,0.92);
    backdrop-filter: blur(10px);
    border-bottom: 1px solid var(--border);
    overflow-x: auto;
    scrollbar-width: none;
  }
  nav.tabs::-webkit-scrollbar { display: none; }
  nav.tabs button {
    flex: 0 0 auto;
    background: none; border: 0; color: var(--muted);
    padding: 12px 16px; font-size: 13px; font-weight: 600;
    border-bottom: 2px solid transparent; cursor: pointer;
    letter-spacing: 0.5px; text-transform: uppercase;
  }
  nav.tabs button.active { color: var(--accent-2); border-bottom-color: var(--accent); }
  nav.tabs button:active { background: var(--card-2); }

  main { padding: 12px var(--pad) 96px; max-width: 720px; margin: 0 auto; }
  .panel { display: none; }
  .panel.active { display: block; }

  .card {
    background: var(--card); border: 1px solid var(--border); border-radius: var(--radius);
    padding: var(--pad); margin-bottom: 12px;
  }
  .card h2 {
    margin: 0 0 10px; font-size: 13px; text-transform: uppercase; letter-spacing: 1px;
    color: var(--accent-2); font-weight: 700;
  }
  label.field { display: block; font-size: 12px; color: var(--muted); margin-bottom: 4px; }
  select, input[type=number], input[type=text], input[type=password] {
    width: 100%; padding: 10px 12px; font-size: 15px; color: var(--fg);
    background: var(--card-2); border: 1px solid var(--border); border-radius: 8px;
    appearance: none; -webkit-appearance: none;
  }
  select:focus, input:focus { outline: 2px solid var(--accent); outline-offset: 0; }
  button.oled {
    width: 100%; padding: 12px 14px; font-size: 15px; font-weight: 700;
    background: var(--accent); color: white; border: 0; border-radius: 8px; cursor: pointer;
    margin-top: 8px;
  }
  button.ghost {
    padding: 10px 14px; font-size: 14px; font-weight: 600;
    background: transparent; color: var(--fg);
    border: 1px solid var(--border); border-radius: 8px; cursor: pointer;
  }
  button.danger {
    background: var(--bad); color: white; border: 0;
  }
  button:active { transform: scale(0.98); }
  button:disabled { opacity: 0.5; cursor: not-allowed; }

  /* Direction radios styled as a pill toggle */
  .toggle {
    display: grid; grid-template-columns: 1fr 1fr; border: 1px solid var(--border);
    border-radius: 8px; overflow: hidden; background: var(--card-2);
  }
  .toggle input { position: absolute; opacity: 0; pointer-events: none; }
  .toggle label {
    text-align: center; padding: 10px 8px; cursor: pointer;
    font-weight: 600; font-size: 13px; color: var(--muted); transition: 0.15s;
    border-right: 1px solid var(--border);
  }
  .toggle label:last-child { border-right: 0; }
  .toggle input:checked + label {
    background: var(--accent); color: white;
  }

  .output {
    border: 1px solid var(--border); border-radius: var(--radius);
    background: var(--card); padding: var(--pad); margin-bottom: 10px;
  }
  .output header { all: unset; display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px; }
  .output h3 { margin: 0; font-size: 16px; }
  .output .id { font-family: ui-monospace, "SF Mono", Menlo, monospace;
    font-size: 11px; color: var(--muted); padding: 2px 6px;
    border: 1px solid var(--border); border-radius: 4px; }
  .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }

  /* Status strip on Status/About cards */
  .kv { display: grid; grid-template-columns: max-content 1fr; gap: 4px 12px; font-size: 14px; }
  .kv .k { color: var(--muted); }
  .kv .v { color: var(--fg); }
  .kv .v.ok { color: var(--good); }
  .kv .v.warn { color: var(--warn); }
  .kv .v.err { color: var(--bad); }

  /* GP visualization */
  .sticks-row { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 8px; }
  .stick { background: var(--card-2); border: 1px solid var(--border); border-radius: 8px;
    padding: 10px; display: flex; flex-direction: column; align-items: center; justify-content: center; }
  .stick .name { font-size: 11px; color: var(--muted); margin-bottom: 4px; }
  .stick canvas { background: #000; border-radius: 6px; }
  .trig { background: var(--card-2); border: 1px solid var(--border); border-radius: 8px;
    padding: 8px 10px; }
  .trig .name { font-size: 11px; color: var(--muted); }
  .trig .bar { height: 8px; background: #000; border-radius: 4px; overflow: hidden; margin-top: 4px; }
  .trig .bar > div { height: 100%; width: 0%; background: var(--accent); transition: width 80ms linear; }
  .btns { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 10px; }
  .btn-chip { padding: 4px 8px; border-radius: 6px; font-size: 11px; font-weight: 700;
    background: var(--card-2); color: var(--muted); border: 1px solid var(--border); }
  .btn-chip.on { background: var(--accent); color: white; border-color: var(--accent); }

  /* Pairing list */
  .mac-list { font-family: ui-monospace, "SF Mono", Menlo, monospace; font-size: 13px;
    background: var(--card-2); padding: 8px 10px; border-radius: 8px; border: 1px solid var(--border); }
  .mac-list .mac { display: block; padding: 2px 0; }

  .toolbar {
    position: fixed; bottom: 0; left: 0; right: 0; z-index: 4;
    background: rgba(15,17,22,0.92); backdrop-filter: blur(8px);
    border-top: 1px solid var(--border);
    padding: 10px var(--pad) calc(10px + env(safe-area-inset-bottom));
    display: flex; gap: 8px;
  }

  .toast {
    position: fixed; left: 50%; top: 16px; transform: translateX(-50%);
    background: var(--card-2); border: 1px solid var(--border);
    padding: 10px 14px; border-radius: 8px; font-size: 13px; z-index: 9; display: none;
  }
  .toast.ok { color: var(--good); }
  .toast.err { color: var(--bad); }
  .meta { font-size: 12px; color: var(--muted); }
  .hint { font-size: 12px; color: var(--muted); margin: 6px 0 0; }
  .hint strong { color: var(--fg); }
  .summary { margin-top: 10px; padding: 8px 10px; border-radius: 8px;
    border: 1px solid var(--border); background: rgba(255,255,255,0.03);
    font-size: 12px; color: var(--muted); }
  .summary strong { color: var(--fg); }
</style>
</head>
<body>

<header>
  <h1>🤖 Combat Robot v2</h1>
  <span class="meta"><span id="hdr-ble" class="dot off"></span><span id="hdr-ble-text">—</span></span>
</header>

<nav class="tabs" role="tablist">
  <button data-tab="controller" class="active">Controller</button>
  <button data-tab="outputs">Outputs</button>
  <button data-tab="settings">Settings</button>
  <button data-tab="about">About</button>
</nav>

<main>
  <!-- ===== Controller tab ===== -->
  <section class="panel active" data-panel="controller">
    <div class="card">
      <h2>8BitDo Ultimate 2 — Live Input</h2>
      <div class="sticks-row">
        <div class="stick"><div class="name">Left Stick (LX, LY)</div><canvas id="ls" width="80" height="80"></canvas></div>
        <div class="stick"><div class="name">Right Stick (RX, RY)</div><canvas id="rs" width="80" height="80"></canvas></div>
      </div>
      <div class="grid-2">
        <div class="trig"><div class="name">LT (Left Trigger)</div><div class="bar"><div id="lt-bar"></div></div></div>
        <div class="trig"><div class="name">RT (Right Trigger)</div><div class="bar"><div id="rt-bar"></div></div></div>
      </div>
      <div class="btns" id="btns"><span class="meta">Waiting for controller…</span></div>
    </div>

    <div class="card">
      <h2>Pairing</h2>
      <p class="meta">Status: <span id="pair-state">—</span></p>
      <div style="display:flex; gap:8px; flex-wrap:wrap;">
        <button id="btn-pair" class="oled" style="flex:1; margin-top:0">Enter Pairing Mode</button>
        <button id="btn-cancel-pair" class="ghost" disabled>Cancel</button>
      </div>
      <p class="meta" style="margin:14px 0 6px;">Paired Controllers</p>
      <div id="mac-list" class="mac-list">—</div>
      <button id="btn-unpair" class="ghost danger" style="width:100%; margin-top:8px;">Clear All Paired Controllers</button>
    </div>
  </section>

  <!-- ===== Outputs tab ===== -->
  <section class="panel" data-panel="outputs">
    <div class="card">
      <h2>Motor &amp; Servo Outputs</h2>
      <p class="meta">For drive motors, choose one signed stick axis as the <strong>Drive input</strong>: above center drives forward, below center drives reverse, center is stop. Use <strong>Direction</strong> only if the motor spins the wrong way. Optional reverse-only input is for trigger/button-style controls.</p>
      <p class="meta"><strong>Drive mode is live:</strong> choose Tank or Arcade below, then Save. The individual output cards are still setup/diagnostic metadata for direction, labels, and future per-output routing.</p>
      <div id="outputs"></div>
    </div>
  </section>

  <!-- ===== Settings tab ===== -->
  <section class="panel" data-panel="settings">
    <div class="card">
      <h2>WiFi</h2>
      <p class="meta">To change WiFi credentials: connect your phone to the robot's AP (<code>Combat-Robot-XXXX</code> / password <code>fightbot</code>), then visit any URL — the captive portal auto-redirects here.</p>
      <div class="kv">
        <span class="k">Mode</span><span class="v" id="wifi-mode">—</span>
        <span class="k">IP</span><span class="v" id="wifi-ip">—</span>
        <span class="k">SSID</span><span class="v" id="wifi-ssid">—</span>
      </div>
      <button id="btn-reset" class="ghost danger" style="width:100%; margin-top:10px;">Reset Outputs to Defaults</button>
    </div>

    <div class="card">
      <h2>Board Revision</h2>
      <p class="meta">v2 (current production) is the default. Override to use v3 if you've flashed the v3 pin map.</p>
      <div class="kv">
        <span class="k">Active rev</span><span class="v" id="board-rev">—</span>
      </div>
      <div class="grid-2" style="margin-top:8px;">
        <button class="ghost" id="btn-board-2">Use v2</button>
        <button class="ghost" id="btn-board-3">Use v3</button>
      </div>
      <button class="ghost" id="btn-board-reset" style="width:100%; margin-top:8px;">Clear Override</button>
    </div>

    <div class="card">
      <h2>Firmware Update (OTA)</h2>
      <form id="ota-form" method="POST" action="/api/ota" enctype="multipart/form-data">
        <label class="field">Upload <code>.bin</code> from your computer</label>
        <input type="file" name="firmware" accept=".bin"
               style="background: var(--card-2); padding: 10px; border-radius: 8px; border: 1px solid var(--border); width: 100%; color: var(--fg);">
        <button type="submit" class="oled">Upload &amp; Update</button>
      </form>
    </div>
  </section>

  <!-- ===== About tab ===== -->
  <section class="panel" data-panel="about">
    <div class="card">
      <h2>Robot Status</h2>
      <div class="kv">
        <span class="k">Firmware</span><span class="v" id="fw-version">—</span>
        <span class="k">Board</span><span class="v" id="fw-board">—</span>
        <span class="k">Battery</span><span class="v" id="fw-battery">—</span>
      </div>
    </div>
    <div class="card">
      <h2>About</h2>
      <p class="meta">Combat Robot v2 controller. BLE-only radio (ESP32-C3-MINI), 4MB flash, NimBLE host.</p>
      <p class="meta">API: <code>GET /api/status</code> · <code>GET /api/config</code> · <code>POST /api/config</code> · <code>WS /ws</code></p>
    </div>
  </section>
</main>

<div class="toolbar" id="toolbar" style="display:none">
  <button class="ghost" id="btn-reload">Reload</button>
  <button class="oled" id="btn-save" style="margin-top:0">Save changes</button>
</div>

<div id="toast" class="toast"></div>

<script>
/* =====================================================================
 * Combat Robot v2 — tabbed mobile-friendly config UI.
 *
 * Tabs (URL hash changes the active tab):
 *   #controller  pairing + live gamepad
 *   #outputs     per-output card editor (direction, source, deadzone)
 *   #settings    WiFi, board rev, OTA
 *   #about       status + links
 *
 * Endpoints used:
 *   GET  /api/status          — board state (also polled for tabs that aren't outputs)
 *   GET  /api/config          — saved output config, polled once on load
 *   GET  /api/config/sources  — input-source list, polled once on load
 *   POST /api/config          — save output config (body = JSON patch)
 *   POST /api/pair/start      — enter pairing mode
 *   POST /api/pair/cancel     — leave pairing mode
 *   POST /api/pair/clear      — clear whitelist
 *   POST /api/board/rev?rev=N — set board rev override
 *   POST /api/board/reset     — clear board rev override
 *   POST /api/ota             — multipart firmware upload
 *   WS   /ws                  — real-time controller state when connected
 * ===================================================================== */

const API_BASE = location.hostname === '' ? 'http://192.168.4.1' : `${location.protocol}//${location.hostname}`;

// ---- Source list (mirrors OC_SRC__COUNT in output_config.h) ------------
const SOURCES = [
  { id: 'NONE',      label: '— none —' },
  { id: 'LX',        label: 'Left Stick X' },
  { id: 'LY',        label: 'Left Stick Y' },
  { id: 'RX',        label: 'Right Stick X' },
  { id: 'RY',        label: 'Right Stick Y' },
  { id: 'LT',        label: 'Left Trigger' },
  { id: 'RT',        label: 'Right Trigger' },
  { id: 'A',         label: 'A Button' },
  { id: 'B',         label: 'B Button' },
  { id: 'X',         label: 'X Button' },
  { id: 'Y',         label: 'Y Button' },
  { id: 'L1',        label: 'L1 Bumper' },
  { id: 'R1',        label: 'R1 Bumper' },
  { id: 'L2',        label: 'L2 (digital)' },
  { id: 'R2',        label: 'R2 (digital)' },
  { id: 'SELECT',    label: 'Select / Share' },
  { id: 'START',     label: 'Start / Options' },
  { id: 'L3',        label: 'L3 (stick click)' },
  { id: 'R3',        label: 'R3 (stick click)' },
  { id: 'HOME',      label: 'Home / PS' },
  { id: 'DPAD_UP',   label: 'D-Pad Up' },
  { id: 'DPAD_DOWN', label: 'D-Pad Down' },
  { id: 'DPAD_LEFT', label: 'D-Pad Left' },
  { id: 'DPAD_RIGHT',label: 'D-Pad Right' },
];
const BUTTONS = ['A','B','X','Y','L1','R1','L2','R2','SELECT','START','L3','R3','HOME'];
const OUTPUTS = [
  { id: 'M1',     display_name: 'Drive Motor 1' },
  { id: 'M2',     display_name: 'Drive Motor 2' },
  { id: 'Weapon', display_name: 'Weapon / ESC'  },
  { id: 'S1',     display_name: 'Servo 1' },
  { id: 'S2',     display_name: 'Servo 2' },
];
const DRIVE_MODES = [
  { id: 'tank_split',   label: 'Tank: left stick = left side, right stick = right side', summary: 'Best for direct combat tank control. Left Stick Y drives M1/left; Right Stick Y drives M2/right.' },
  { id: 'arcade_left',  label: 'Arcade: left stick throttle + turn', summary: 'One-stick arcade. Left Stick Y controls speed; Left Stick X controls steering.' },
  { id: 'arcade_right', label: 'Arcade: right stick throttle + turn', summary: 'One-stick arcade on the right stick. Right Stick Y controls speed; Right Stick X controls steering.' },
  { id: 'arcade_split', label: 'Split arcade: left stick speed + right stick steering', summary: 'Two-stick arcade. Left Stick Y controls speed; Right Stick X controls left/right direction.' },
];

// ---- In-memory state, seeded from /api/config when loaded -------------
const state = {
  drive_mode: 'tank_split',
  outputs: {
    M1:     { direction: 'normal',  servo_mode: 'bi',  deadzone: 10, primary: 'LY', secondary: 'NONE' },
    M2:     { direction: 'normal',  servo_mode: 'bi',  deadzone: 10, primary: 'RY', secondary: 'NONE' },
    Weapon: { direction: 'normal',  servo_mode: 'bi',  deadzone:  5, primary: 'RT', secondary: 'NONE' },
    S1:     { direction: 'normal',  servo_mode: 'uni', deadzone: 10, primary: 'NONE', secondary: 'NONE' },
    S2:     { direction: 'normal',  servo_mode: 'uni', deadzone: 10, primary: 'NONE', secondary: 'NONE' },
  },
  gp: null,
  bleConnected: false,
  pairingActive: false,
  pairedMacs: [],
  wifi: { mode: '—', ip: '—', ssid: '—' },
  board: { rev: '—' },
  battery: { mv: '—', state: '—' },
};

// ---- DOM helpers --------------------------------------------------------
function el(tag, attrs = {}, children = []) {
  const e = document.createElement(tag);
  for (const k in attrs) {
    if (k === 'class') e.className = attrs[k];
    else if (k.startsWith('on')) e.addEventListener(k.slice(2), attrs[k]);
    else e.setAttribute(k, attrs[k]);
  }
  const arr = Array.isArray(children) ? children : [children];
  for (const c of arr) {
    if (c == null) continue;
    e.appendChild(typeof c === 'string' ? document.createTextNode(c) : c);
  }
  return e;
}

function sourceSelect(name, value) {
  const sel = el('select', { 'data-name': name });
  for (const s of SOURCES) {
    const o = el('option', { value: s.id }, s.label);
    if (s.id === value) o.selected = true;
    sel.appendChild(o);
  }
  return sel;
}

function directionToggle(name, value) {
  const wrap = el('div', { class: 'toggle' });
  const make = (val, label) => {
    const inp = el('input', { type: 'radio', name: `dir-${name}`, id: `dir-${name}-${val}`, value: val });
    if (val === value) inp.checked = true;
    const lab = el('label', { for: inp.id }, label);
    return [inp, lab];
  };
  // The input MUST come immediately before its label; CSS uses
  // `.toggle input:checked + label` so the selected option is highlighted.
  for (const [inp, lab] of [make('normal', 'Normal'), make('reversed', 'Reversed')]) {
    wrap.appendChild(inp);
    wrap.appendChild(lab);
  }
  return wrap;
}

// ---- Tabs --------------------------------------------------------------
function showTab(name) {
  document.querySelectorAll('nav.tabs button').forEach(b => {
    b.classList.toggle('active', b.dataset.tab === name);
  });
  document.querySelectorAll('.panel').forEach(p => {
    p.classList.toggle('active', p.dataset.panel === name);
  });
  // Save toolbar is only useful on Outputs
  document.getElementById('toolbar').style.display = (name === 'outputs') ? 'flex' : 'none';
  if (location.hash !== '#' + name) {
    history.replaceState(null, '', '#' + name);
  }
}
document.querySelectorAll('nav.tabs button').forEach(b => {
  b.addEventListener('click', () => showTab(b.dataset.tab));
});
const TAB_NAMES = ['controller', 'outputs', 'settings', 'about'];
function tabFromHash() {
  const h = (location.hash || '#controller').slice(1);
  return TAB_NAMES.includes(h) ? h : 'controller';
}
showTab(tabFromHash());
window.addEventListener('hashchange', () => showTab(tabFromHash()));

// ---- Output cards ------------------------------------------------------
function sourceLabel(id) {
  const src = SOURCES.find(s => s.id === id);
  return src ? src.label.replace('— none —', 'none') : id;
}

function driveModeSummary(mode) {
  const m = DRIVE_MODES.find(x => x.id === mode) || DRIVE_MODES[0];
  return m.summary;
}

function renderDriveModeCard() {
  const card = el('article', { class: 'output drive-mode' });
  card.appendChild(el('header', {}, [
    el('h3', {}, 'Driving Style'),
    el('span', { class: 'id' }, 'live'),
  ]));
  const sel = el('select', { 'data-name': 'drive_mode' });
  for (const m of DRIVE_MODES) {
    const opt = el('option', { value: m.id }, m.label);
    if (m.id === state.drive_mode) opt.selected = true;
    sel.appendChild(opt);
  }
  sel.addEventListener('change', e => {
    state.drive_mode = e.target.value;
    renderOutputs();
  });
  card.appendChild(el('div', { class: 'grid-2' }, [
    el('div', {}, [
      el('label', { class: 'field' }, 'Drive mode'),
      sel,
      el('p', { class: 'hint' }, 'Saved to NVS and used by the runtime drive mixer after Save.'),
    ]),
    el('div', {}, [
      el('label', { class: 'field' }, 'Runtime mapping'),
      el('p', { class: 'summary' }, driveModeSummary(state.drive_mode)),
    ]),
  ]));
  return card;
}

function motorMappingSummary(cfg) {
  const drive = sourceLabel(cfg.primary);
  const reverse = cfg.secondary && cfg.secondary !== 'NONE' ? sourceLabel(cfg.secondary) : null;
  const reversed = cfg.direction === 'reversed';
  const dir = reversed ? 'Reversed' : 'Normal';
  if (!cfg.primary || cfg.primary === 'NONE') {
    return `${dir}: no drive input assigned yet.`;
  }
  if (['LX','LY','RX','RY'].includes(cfg.primary)) {
    if (reversed) {
      return `Reversed: ${drive} is assigned, but this motor output is flipped — above center sends reverse output, below center sends forward output.`;
    }
    return `Normal: ${drive} above center = forward, below center = reverse, center = stop. If the physical motor spins the wrong way, choose Reversed.`;
  }
  if (reverse) {
    return `${dir}: ${drive} drives forward/on; ${reverse} drives reverse/off.${reversed ? ' Output is flipped.' : ''}`;
  }
  return `${dir}: ${drive} drives forward/on. Add a reverse-only input if needed.${reversed ? ' Output is flipped.' : ''}`;
}

function renderOutput(o) {
  // Defensive: if /api/config returned a key we don't have seeded
  // (or `Reset Outputs to Defaults` raced a save), seed minimal defaults
  // rather than throw on cfg.direction.
  if (!state.outputs[o.id]) state.outputs[o.id] = {
    direction: 'normal', servo_mode: 'bi', deadzone: 10,
    primary: 'NONE', secondary: 'NONE',
  };
  const cfg = state.outputs[o.id];
  const card = el('article', { class: 'output', 'data-out': o.id });

  const dirWrap = directionToggle(o.id, cfg.direction);
  dirWrap.addEventListener('change', e => {
    if (e.target.checked) {
      state.outputs[o.id].direction = e.target.value;
      renderOutputs();
    }
  });

  const isServo = (o.id === 'S1' || o.id === 'S2');
  const servoSel = el('select', { 'data-name': 'servo_mode' },
    [ el('option', { value: 'bi'  }, 'Bidirectional'),
      el('option', { value: 'uni' }, 'Uni-directional') ]);
  if (cfg.servo_mode === 'uni') servoSel.value = 'uni';
  servoSel.addEventListener('change', e => { state.outputs[o.id].servo_mode = e.target.value; });

  const primary = sourceSelect('primary', cfg.primary);
  primary.addEventListener('change', e => { state.outputs[o.id].primary = e.target.value; renderOutputs(); });
  const secondary = sourceSelect('secondary', cfg.secondary);
  secondary.addEventListener('change', e => { state.outputs[o.id].secondary = e.target.value; renderOutputs(); });

  const dz = el('input', { type: 'number', min: '0', max: '50', step: '1', value: String(cfg.deadzone) });
  dz.addEventListener('change', e => {
    const v = Math.max(0, Math.min(50, parseInt(e.target.value || '0', 10)));
    state.outputs[o.id].deadzone = v;
  });

  card.appendChild(el('header', {}, [
    el('h3', {}, o.display_name),
    el('span', { class: 'id' }, o.id),
  ]));

  const grid = el('div', { class: 'grid-2' });
  grid.appendChild(el('div', {}, [
    el('label', { class: 'field' }, 'Direction'),
    dirWrap,
  ]));

  const second = el('div');
  if (isServo) {
    second.appendChild(el('label', { class: 'field' }, 'Servo mode'));
    second.appendChild(servoSel);
  } else {
    second.appendChild(el('label', { class: 'field' }, 'Optional reverse-only input'));
    second.appendChild(secondary);
    second.appendChild(el('p', { class: 'hint' }, 'Leave this as none when using a signed stick axis like Left Stick Y.'));
  }
  grid.appendChild(second);
  card.appendChild(grid);

  const grid2 = el('div', { class: 'grid-2', style: 'margin-top:10px' });
  grid2.appendChild(el('div', {}, [
    el('label', { class: 'field' }, isServo ? 'Primary input' : 'Drive input (center = stop)'),
    primary,
    !isServo ? el('p', { class: 'hint' }, 'Example: Left Stick Y above center = forward, below center = reverse.') : null,
  ]));

  if (isServo) {
    grid2.appendChild(el('div', {}, [
      el('label', { class: 'field' }, 'Secondary input'),
      secondary,
    ]));
  } else {
    grid2.appendChild(el('div', {}, [
      el('label', { class: 'field' }, 'Deadzone (%)'),
      dz,
    ]));
  }
  card.appendChild(grid2);
  if (!isServo) {
    card.appendChild(el('div', { class: 'summary' }, [
      el('strong', {}, 'Mapping: '),
      motorMappingSummary(state.outputs[o.id]),
    ]));
  }
  return card;
}

function renderOutputs() {
  const root = document.getElementById('outputs');
  root.innerHTML = '';
  root.appendChild(renderDriveModeCard());
  for (const o of OUTPUTS) root.appendChild(renderOutput(o));
}

// ---- Live controller visualization -------------------------------------
function renderButtonChips(gp) {
  const root = document.getElementById('btns');
  root.innerHTML = '';
  const buttons = (gp && typeof gp.buttons === 'number') ? gp.buttons : 0;
  const dpad = (gp && typeof gp.dpad === 'number') ? gp.dpad : 0;
  if (!gp) {
    root.appendChild(el('span', { class: 'meta' }, 'Waiting for controller…'));
    return;
  }
  for (const [i, b] of BUTTONS.entries()) {
    root.appendChild(el('span', { class: 'btn-chip' + ((buttons >> i) & 1 ? ' on' : '') }, b));
  }
  for (const [i, d] of [['↑',0x01],['↓',0x02],['←',0x04],['→',0x08]]) {
    root.appendChild(el('span', { class: 'btn-chip' + ((dpad & d) ? ' on' : '') }, d));
  }
}

function drawStick(canvas, lx, ly) {
  const ctx = canvas.getContext('2d');
  const w = canvas.width, h = canvas.height;
  ctx.fillStyle = '#000'; ctx.fillRect(0, 0, w, h);
  ctx.strokeStyle = '#2a2f3a'; ctx.lineWidth = 1;
  ctx.strokeRect(0.5, 0.5, w-1, h-1);
  ctx.strokeStyle = '#333';
  ctx.beginPath(); ctx.moveTo(w/2, 0); ctx.lineTo(w/2, h); ctx.moveTo(0, h/2); ctx.lineTo(w, h/2); ctx.stroke();
  const cx = w/2 + (lx / 512) * (w/2 - 6);
  const cy = h/2 + (ly / 512) * (h/2 - 6);
  ctx.fillStyle = '#ff6b35';
  ctx.beginPath(); ctx.arc(cx, cy, 6, 0, Math.PI * 2); ctx.fill();
}

function liveTick() {
  // Clamp every field on state.gp so a partial WS frame never throws.
  const gp = state.gp;
  const lx = (gp && typeof gp.lx === 'number') ? gp.lx : 0;
  const ly = (gp && typeof gp.ly === 'number') ? gp.ly : 0;
  const rx = (gp && typeof gp.rx === 'number') ? gp.rx : 0;
  const ry = (gp && typeof gp.ry === 'number') ? gp.ry : 0;
  const lt = (gp && typeof gp.lt === 'number') ? gp.lt : 0;
  const rt = (gp && typeof gp.rt === 'number') ? gp.rt : 0;
  drawStick(document.getElementById('ls'), lx, ly);
  drawStick(document.getElementById('rs'), rx, ry);
  document.getElementById('lt-bar').style.width = (lt / 1023 * 100).toFixed(1) + '%';
  document.getElementById('rt-bar').style.width = (rt / 1023 * 100).toFixed(1) + '%';
  renderButtonChips(gp);
}

function setBle(on) {
  state.bleConnected = !!on;
  const dot = document.getElementById('hdr-ble');
  const text = document.getElementById('hdr-ble-text');
  if (!dot || !text) return;
  dot.classList.toggle('on', state.bleConnected);
  dot.classList.toggle('off', !state.bleConnected);
  text.textContent = state.bleConnected ? 'Connected' : 'Disconnected';
}

// ---- Toast --------------------------------------------------------------
function toast(msg, kind='ok') {
  const t = document.getElementById('toast');
  t.className = 'toast ' + kind;
  t.textContent = msg;
  t.style.display = 'block';
  setTimeout(() => { t.style.display = 'none'; }, 2200);
}

// ---- API calls ----------------------------------------------------------
async function apiGet(path) {
  const r = await fetch(`${API_BASE}${path}`);
  if (!r.ok) throw new Error(`HTTP ${r.status}`);
  return await r.json();
}
async function apiPost(path) {
  const r = await fetch(`${API_BASE}${path}`, { method: 'POST' });
  if (!r.ok) throw new Error(`HTTP ${r.status}`);
  return r.json().catch(() => ({}));
}
async function apiPostJSON(path, body) {
  const r = await fetch(`${API_BASE}${path}`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!r.ok) throw new Error(`HTTP ${r.status}`);
  return r.json().catch(() => ({}));
}

// ---- Save / Reset wiring -----------------------------------------------
function editableOutputPatch(outputs) {
  const patch = { drive_mode: state.drive_mode };
  for (const [id, cfg] of Object.entries(outputs)) {
    patch[id] = {
      direction: cfg.direction,
      servo_mode: cfg.servo_mode,
      deadzone: cfg.deadzone,
      primary: cfg.primary,
      secondary: cfg.secondary,
    };
  }
  return patch;
}

document.getElementById('btn-save').addEventListener('click', async () => {
  try {
    await apiPostJSON('/api/config', editableOutputPatch(state.outputs));
    toast('Saved to NVS');
  } catch (e) { toast('Save failed: ' + e.message, 'err'); }
});

document.getElementById('btn-reset').addEventListener('click', () => {
  if (!confirm('Reset all outputs to defaults? (this just reverts the form — click Save to persist)')) return;
  state.drive_mode = 'tank_split';
  state.outputs = {
    M1:     { direction: 'normal', servo_mode: 'bi',  deadzone: 10, primary: 'LY', secondary: 'NONE' },
    M2:     { direction: 'normal', servo_mode: 'bi',  deadzone: 10, primary: 'RY', secondary: 'NONE' },
    Weapon: { direction: 'normal', servo_mode: 'bi',  deadzone:  5, primary: 'RT', secondary: 'NONE' },
    S1:     { direction: 'normal', servo_mode: 'uni', deadzone: 10, primary: 'NONE', secondary: 'NONE' },
    S2:     { direction: 'normal', servo_mode: 'uni', deadzone: 10, primary: 'NONE', secondary: 'NONE' },
  };
  renderOutputs();
  toast('Defaults restored in form');
});

document.getElementById('btn-reload').addEventListener('click', () => location.reload());

// ---- Pairing wiring ----------------------------------------------------
document.getElementById('btn-pair').addEventListener('click', async () => {
  try { await apiPost('/api/pair/start'); toast('Pairing mode ON'); refreshStatus(); }
  catch (e) { toast('Pair start failed: ' + e.message, 'err'); }
});
document.getElementById('btn-cancel-pair').addEventListener('click', async () => {
  try { await apiPost('/api/pair/cancel'); toast('Pairing mode OFF'); refreshStatus(); }
  catch (e) { toast('Cancel failed: ' + e.message, 'err'); }
});
document.getElementById('btn-unpair').addEventListener('click', async () => {
  if (!confirm('Clear all paired controllers? You will need to re-pair.')) return;
  try { await apiPost('/api/pair/clear'); toast('Paired list cleared'); refreshStatus(); }
  catch (e) { toast('Clear failed: ' + e.message, 'err'); }
});

// ---- Board rev wiring ---------------------------------------------------
document.getElementById('btn-board-2').addEventListener('click', async () => {
  try { await apiPost('/api/board/rev?rev=2'); toast('Board rev set to 2 (effective on next boot)'); refreshStatus(); }
  catch (e) { toast('Failed: ' + e.message, 'err'); }
});
document.getElementById('btn-board-3').addEventListener('click', async () => {
  try { await apiPost('/api/board/rev?rev=3'); toast('Board rev set to 3 (effective on next boot)'); refreshStatus(); }
  catch (e) { toast('Failed: ' + e.message, 'err'); }
});
document.getElementById('btn-board-reset').addEventListener('click', async () => {
  try { await apiPost('/api/board/reset'); toast('Override cleared'); refreshStatus(); }
  catch (e) { toast('Failed: ' + e.message, 'err'); }
});

// ---- /api/status polling -----------------------------------------------
function applyStatus(s) {
  state.pairingActive = (s.pairing_state === 'ACCEPT');
  document.getElementById('pair-state').textContent = s.pairing_state || '—';
  document.getElementById('btn-pair').disabled = state.pairingActive;
  document.getElementById('btn-cancel-pair').disabled = !state.pairingActive;
  const wifiMode = s.wifi_ap_mode ? 'AP' : (s.wifi_connected ? 'STA' : '—');
  document.getElementById('wifi-mode').textContent = wifiMode;
  document.getElementById('wifi-ip').textContent = s.wifi_ip || '—';
  document.getElementById('wifi-ssid').textContent = wifiMode === 'AP' ? (s.wifi_ap_mode ? '(this AP)' : '—') : '—';
  document.getElementById('fw-version').textContent = s.firmware_version || '—';
  document.getElementById('fw-battery').textContent =
    s.battery_mv ? `${(s.battery_mv/1000).toFixed(2)} V (state ${s.battery_state})` : '—';
  document.getElementById('board-rev').textContent = 'v2 (compile-time)';
  // Drive the BLE header dot from the polled /api/status truth so the
  // indicator reflects reality even before the first WS frame arrives
  // (or after a board reboot before reconnect).
  setBle(!!s.ble_connected);
  // Paired MACs
  const list = document.getElementById('mac-list');
  if (s.paired_macs && s.paired_macs.length) {
    list.innerHTML = '';
    for (const m of s.paired_macs) list.appendChild(el('span', { class: 'mac' }, m));
  } else {
    list.textContent = 'No controllers paired';
  }
  }

async function refreshStatus() {
  try {
    const s = await apiGet('/api/status');
    applyStatus(s);
  } catch (e) { /* offline / not yet ready */ }
}

// ---- /api/config loader (populates Outputs tab) ------------------------
async function loadConfig() {
  try {
    const j = await apiGet('/api/config');
    if (DRIVE_MODES.some(m => m.id === j.drive_mode)) state.drive_mode = j.drive_mode;
    for (const k of Object.keys(j.outputs || {})) {
      if (state.outputs[k]) state.outputs[k] = j.outputs[k];
    }
    renderOutputs();
  } catch (e) { /* defaults shown */ }
}

// ---- WebSocket live feed (only when controller is connected) ----------
let ws;
function connectWS() {
  try {
    const proto = (location.protocol === 'https:') ? 'wss' : 'ws';
    ws = new WebSocket(`${proto}://${location.host}/ws`);
    ws.onopen = () => { window.__USE_LIVE__ = true; };
    ws.onclose = () => { window.__USE_LIVE__ = false; setTimeout(connectWS, 2000); };
    ws.onerror = () => { try { ws.close(); } catch(e) {} };
    ws.onmessage = (ev) => {
      try {
        const msg = JSON.parse(ev.data);
        if (msg.type === 'state') {
          setBle(!!msg.connected);
          state.gp = msg.connected ? msg.state : null;
          if (msg.pairing) {
            state.pairingActive = (msg.pairing === 'ACCEPT');
            const el = document.getElementById('pair-state');
            if (el) el.textContent = msg.pairing;
            const btn = document.getElementById('btn-pair');
            const cBtn = document.getElementById('btn-cancel-pair');
            if (btn) btn.disabled = state.pairingActive;
            if (cBtn) cBtn.disabled = !state.pairingActive;
          }
        }
      } catch (e) {}
    };
  } catch (e) {}
}

// ---- Boot ---------------------------------------------------------------
setBle(false);
renderOutputs();
connectWS();
loadConfig();
refreshStatus();
setInterval(() => { liveTick(); refreshStatus(); }, 1000);
setInterval(liveTick, 50);
</script>
</body>
</html>

)rawliteral";
