#!/usr/bin/env python
"""Generate components/web_config/src/web_index_gen.h from docs/config-ui-mockup.html.

The mockup is now self-contained: it already POSTs to /api/config, connects
to /ws, etc. The generator's only job is to escape the raw-literal
delimiter and emit the file as PROGMEM-friendly C source.
"""
from __future__ import annotations
import pathlib, time

PROJECT_ROOT = pathlib.Path(r"C:\Users\kbrow\Documents\Codex\combat-robot-v2")
SRC = PROJECT_ROOT / "docs" / "config-ui-mockup.html"
OUT = PROJECT_ROOT / "components" / "web_config" / "src" / "web_index_gen.h"


def main() -> int:
    if not SRC.exists():
        print(f"missing source: {SRC}")
        return 1
    html = SRC.read_text()

    # Avoid breaking the raw literal: change the literal delimiter if present.
    safe = html.replace(")rawliteral", ")rawliteral-STOP-HERE")

    body = (
        "// This file is generated by tools/gen_web_index.py from\n"
        "// docs/config-ui-mockup.html. Do not edit by hand.\n\n"
        "#pragma once\n\n"
        f"// Generated {time.strftime('%Y-%m-%dT%H:%M:%S')} from docs/config-ui-mockup.html\n"
        f"// Source size: {len(html)} bytes\n"
        f"static const char INDEX_HTML[] PROGMEM = R\"rawliteral(\n"
        + safe + "\n)rawliteral\";\n"
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body)
    print(f"wrote {OUT} ({len(body)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
